# Generated by Django 5.2.12 on 2026-10-04 03:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_coordinator(apps, schema_editor):
    apps.get_model("ai_jobs", "AIJobCoordinator").objects.using(
        schema_editor.connection.alias
    ).get_or_create(id=1)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        ("grading", "0002_criterion_results"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIJobCoordinator",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("questions", "Extract questions"),
                            ("reference_answers", "Generate reference answers"),
                            ("rubric", "Generate rubric"),
                            ("grade_submission", "Grade submission"),
                            ("grade_batch", "Grade batch"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("retry_wait", "Waiting to retry"),
                            ("paused_quota", "Paused by quota"),
                            ("needs_attention", "Needs attention"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("superseded", "Inputs changed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=10)),
                (
                    "request_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("input_snapshot", models.JSONField()),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("completed_steps", models.PositiveIntegerField(default=0)),
                ("total_steps", models.PositiveIntegerField(default=0)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=40)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("result_reference", models.JSONField(blank=True, default=dict)),
                ("retry_after", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assignments.assignment",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ai_jobs.aijob",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grading.studentsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="AIJobStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("position", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("retry_wait", "Waiting to retry"),
                            ("paused_quota", "Paused by quota"),
                            ("needs_attention", "Needs attention"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("superseded", "Inputs changed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("checkpoint", models.JSONField(blank=True, default=dict)),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="ai_jobs.aijob",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="AIJobAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("claim_token", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Usage reserved"),
                            ("dispatched", "Request dispatched"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed safely"),
                            ("uncertain", "Response or billing unknown"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("provider_request_id", models.CharField(blank=True, max_length=100)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "usage",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grading.llmusage",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="ai_jobs.aijobstep",
                    ),
                ),
            ],
            options={
                "ordering": ("number", "id"),
            },
        ),
        migrations.CreateModel(
            name="AIJobTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="ai_jobs.aijob",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["owner", "state", "created_at"], name="ai_job_owner_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(fields=["state", "priority", "created_at"], name="ai_job_queue_idx"),
        ),
        migrations.AddConstraint(
            model_name="aijob",
            constraint=models.UniqueConstraint(
                fields=("owner", "request_key"), name="ai_job_request_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="aijob",
            constraint=models.CheckConstraint(
                condition=models.Q(("completed_steps__lte", models.F("total_steps"))),
                name="ai_job_progress_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="aijobstep",
            constraint=models.UniqueConstraint(fields=("job", "key"), name="ai_job_step_once"),
        ),
        migrations.AddIndex(
            model_name="aijobstep",
            index=models.Index(fields=["state", "lease_expires_at"], name="ai_step_lease_idx"),
        ),
        migrations.AddConstraint(
            model_name="aijobstep",
            constraint=models.UniqueConstraint(
                fields=("job", "position"), name="ai_job_step_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="aijobattempt",
            constraint=models.UniqueConstraint(
                fields=("step", "number"), name="ai_job_attempt_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="aijobtarget",
            constraint=models.UniqueConstraint(fields=("job", "key"), name="ai_job_target_once"),
        ),
        migrations.AddConstraint(
            model_name="aijobtarget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("key",),
                name="ai_job_active_target",
            ),
        ),
        migrations.RunPython(create_coordinator, migrations.RunPython.noop),
    ]
